version: '3.1'
services:
  middleware:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
